# Quickstart

In [1]:
import time
import numpy as np
import pandas as pd
import mlx.core as mx
from rdkit import Chem
from mlx_cluster import fp_to_mlx, get_tanimoto, butina, KMeans, FPGenerator

Helper Function

In [2]:
def total_time(total_time):
    total = float(round(total_time, 2))
    print(f"Total Time: {total} Sec")

# Data Prep
Dataset pulled from [BitBirch](https://github.com/mqcomplab/bblean.git)

In [3]:
# load molecules
df = pd.read_csv("dataset/chembl-33-natural-products-subset.smi", sep='\t', names=['smiles'], header=None)

# take first 10_000 molecules
smi_list = df['smiles'][:10_000].tolist()

print(f"The number of molecules for clustering: {len(smi_list)}")

The number of molecules for clustering: 10000


# Molecular Fingerprint
Fingerprints can be generated as usual using RDKit. However, this the modern RDKit fingerprint generation method has been wrapped into the **Generate()** class. This class can speed up fingerprint generation by using multiple cpus. The smiles strings needs to first be converted into a list or np.array of RDMols before proceeding. Converting the smi_list into a list/array of rdkit molecular objects can also be used. Here we will keep things simple and use a list/array of smiles strings.

In [4]:
# can be a list or np.array of smiles strings or ROMols.
fp_gen = FPGenerator(smi_list)
rdkit_fps = fp_gen.fingerprint(type='rdkit', nbits=1024, n_cpu=10)

Afterwards, the fingerprints must be converted into type mx.array(). This can be done in two lines or by using the support method **fp_to_mlx()**.

In [5]:
np_array = np.array(rdkit_fps)
mlx_fp = mx.array(np_array).astype(mx.float32)

# # optional support function to convert fp list into mx.array()
# mlx_fp = fp_to_mlx(rdkit_fps)

# Clustering

Currently, two clustering algorithms are available - Butina and KMeans.

## Generating Tanimoto Similarity Score
For Butina, this requires generating Tanimoto similarity scores between a list of molecules. This is handled internally in the **butina()** method. However, as Tanimoto score is calculated on mx.arrays, this can also be done quickly on the apple silicon as follows:

In [6]:
score = get_tanimoto(mlx_fp, output='array')
score

array([0.6756757 , 0.93318486, 0.9736842 , ..., 0.37985438, 0.3532338 ,
       0.10736579], shape=(49995000,), dtype=float32)

## Butina Clustering
The butina clustering is done by using the **butina()** method and giving it the mlx fingerprint array. The output will give the output as a list of clusters, with the first entry of a cluster being the centroid.

In [7]:
# record time
start = time.time()

butina_mlx = butina(mlx_fp)

# end time
end = time.time()
total_time(end - start)

Total Time: 0.33 Sec


In [8]:
print(f"Number of clusters: {len(butina_mlx)}")

Number of clusters: 2525


## KMeans
The Kmeans clustering should mimic what is seen with Scikit-Learn. The number of clusters are specified and then generated. The clusters and the centroids can also be extracted using support methods, as demoed below.

In [9]:
# record time
start = time.time()

# define and fit the model
kmeans = KMeans(n_clusters=200, random_state=0).fit(mlx_fp)

# end time
end = time.time()
total_time(end-start)

Total Time: 0.32 Sec


Extracting cluster and centroids.

In [10]:
# cluster labels
kcluster = np.array(kmeans.labels_)
kcluster

array([ 87,  87,  67, ..., 129,  88,  88], shape=(10000,), dtype=uint32)

In [11]:
# cluster centroid
kcentroid, _ = np.array(kmeans.pairwise_distances_argmin_min(mlx_fp))
kcentroid

array([3150., 2526.,  154., 5739., 8317.,  953., 6902., 8652.,  640.,
       4697., 2312., 7034., 6921., 7161., 1479., 8379., 5105., 7971.,
        143., 1950., 7700., 2256., 6918., 1340., 5329., 1119., 3037.,
       4607.,   58., 4930., 3985., 9837., 2871.,  760.,  923., 7856.,
        365., 5450., 7667., 4156., 2256., 7602., 3564., 4284., 8973.,
       3237., 5422., 6415., 7401., 7129., 4539., 4729., 8101., 4673.,
        110., 5827.,   35., 6910., 1226., 7167.,  141.,  856., 9466.,
        826., 3994., 5286., 6671., 5560., 5724., 4352., 2109., 6018.,
        937., 2829., 5106., 7267., 4127., 6821., 6805., 3711., 8176.,
        504., 2728.,  446., 8159., 1901.,   32., 5391., 8310., 6222.,
       7824., 1120., 2248., 7923., 6757., 4460., 1271., 9526., 3303.,
       9153., 8459., 6859., 2963., 6400., 7758., 1205., 3957., 1983.,
       2802., 7387.,   48., 5042., 4646., 4054., 7673., 4817., 3400.,
       3582., 1799., 1313., 1234., 6454., 4408., 3836., 5715., 5681.,
       5099., 3343.,

In [12]:
print(f"Number of clusters: {len(kcentroid)}")

Number of clusters: 200
